### ISSUE TITLE
Is there a way to pull out the current subset?

### ISSUE THREAD

**Issue by mauriziocalarese** [Botre/vue-lpage#5]
Hi,
as the subject says, I would like to pull out the current subset from the slot scope, to feed another component with that data.

Is there a way to do this?
I could also use the vuex store.

Thanks in advance.

**Comment by botre** [comment]
Does the following not work for you?

```
    <div slot-scope="{ subset }">
      <another-component :data="subset"></another-component>
    </div>
```

**Comment by botre** [comment]
If you want to feed it to a component **outside** of the slot then no, this is not possible.

**Comment by mauriziocalarese** [comment]
Yes, sorry, I forgot to specify outside.

Anyway, I solved using Vuex, taking inspiration from your source code.

Many thanks :)
